### ISSUE TITLE
Binary for Mac

### ISSUE THREAD

**Issue by cdimitroulas** [samhh/tshm#54]
Hello, thanks for this lovely utility!

I have been using it for some time on my linux machine, however I'm not being forced to use a Macbook for certain work that I need to do and I would love to continue using tshm. Would it be difficult to add an extra step in the CI to build another binary suited for Mac (M1 chip)?

**Comment by samhh** [comment]
As a first step, does the binary here work for you?: https://github.com/samhh/tshm/releases/tag/0.4.1

**Comment by cdimitroulas** [comment]
@samhh I just did a couple of basic tests with it and it seems to work!
